name: wrkflw
on: workflow_dispatch

jobs:
  printing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: list statement
        run: |
          whoami
          cd src
          ls -lstr

  newdir:
    needs: printing
    runs-on: ubuntu-latest
    steps:
      - name: create new dir
        run: |
          mkdir temp
          cp /src/print_value.py /temp/newfile.py
          ls -lstr
          python3 newfile.py
      
